modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "${mod_author}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
versionRange = "1.20.1"
mandatory = true

[[dependencies.${mod_id}]]
modId = "nirvana_lib"
mandatory = true
versionRange = "[${lib_version},)"
ordering = "AFTER"
side = "CLIENT"